Ensured that temporary files are deleted on exit, whether ordinarily or because process is killed Removed duplication of init code Adapted sha-bang to use /usr/bin/env instead to work on FreeBSD systems Use exec to run curl so that process is effectively a curl init script
git-svn-id: http://s3-bash.googlecode.com/svn/trunk@7 437c54f9-5d38-0410-a777-75cbac79620a

diff --git a/s3-common-functions b/s3-common-functions
--- a/s3-common-functions
+++ b/s3-common-functions
@@ -1,4 +1,4 @@
-#! /bin/bash
+#! /usr/bin/env bash
 cat > /dev/null << EndOfLicence
 s3-bash
 Copyright 2007 Raphael James Cohn
@@ -20,14 +20,21 @@ set -u
 set -e
 
 # Constants
-readonly version="0.01"
+readonly version="0.02"
+readonly userSpecifiedDataErrorExitCode=1
+readonly invalidCommandLineOption=2
+readonly internalErrorExitCode=3
+readonly invalidEnvironmentExitCode=4
 readonly ipadXorByte=0x36
 readonly opadXorByte=0x5c
 
-# Commands like aliases
+# Command-like aliases
 readonly sha1="openssl dgst -sha1 -binary"
 readonly base64encode="openssl enc -base64 -e -in"
 readonly base64decode="openssl enc -base64 -d -in"
+
+# Globals
+declare -a temporaryFiles
 
 function base64EncodedMD5
 {
@@ -45,49 +52,88 @@ function printErrorHelpAndExit
 	printHelpAndExit $2
 }
 
-function checkEnvironment()
+function checkProgramIsInEnvironment
 {
-	if [ ! -x "$(which openssl)" ]; then
-		printErrorHelpAndExit "openssl not found on the path or not executable" 2
-	elif [ ! -x "$(which curl)" ]; then
-		printErrorHelpAndExit "curl not found on the path or not executable" 2
-	elif [ ! -x "$(which od)" ]; then
-		printErrorHelpAndExit "od not found on the path or not executable" 2
-	elif [ ! -x "$(which dd)" ]; then
-		printErrorHelpAndExit "dd not found on the path or not executable" 2
-	elif [ ! -x "$(which printf)" ]; then
-		printErrorHelpAndExit "printf not found on the path or not executable" 2
-	elif [ ! -x "$(which sed)" ]; then
-		printErrorHelpAndExit "sed not found on the path or not executable" 2
-	elif [ ! -x "$(which awk)" ]; then
-		printErrorHelpAndExit "awk not found on the path or not executable" 2
-	elif [ ! -x "$(which sort)" ]; then
-		printErrorHelpAndExit "sort not found on the path or not executable" 2
-	elif [ ! -x "$(which mktemp)" ]; then
-		printErrorHelpAndExit "mktemp not found on the path or not executable" 2
-	elif [ ! -x "$(which rm)" ]; then
-		printErrorHelpAndExit "rm not found on the path or not executable" 2
-	elif [ ! -x "$(which grep)" ]; then
-		printErrorHelpAndExit "grep not found on the path or not executable" 2
-	elif [ ! -x "$(which cp)" ]; then
-		printErrorHelpAndExit "cp not found on the path or not executable" 2
-	elif [ ! -x "$(which ls)" ]; then
-		printErrorHelpAndExit "ls not found on the path or not executable" 2
-	elif [ ! -x "/bin/bash" ]; then
-		printErrorHelpAndExit "/bin/bash not found or not executable" 2
+	if [ ! -x "$(which $1)" ]; then
+		printErrorHelpAndExit "Environment Error: $1 not found on the path or not executable" $invalidEnvironmentExitCode
 	fi
+}
+
+# Do not use this from directly. Due to a bug in bash, array assignments do not work when the function is used with command substitution
+function createTemporaryFile
+{
+	local temporaryFile="$(mktemp "$temporaryDirectory/$$.$1.XXXXXXXX")" || printErrorHelpAndExit "Environment Error: Could not create a temporary file. Please check you /tmp folder permissions allow files and folders to be created and disc space." $invalidEnvironmentExitCode
+	local length="${#temporaryFiles[@]}"
+	temporaryFiles[$length]="$temporaryFile"
+}
+
+function mostRecentTemporaryFile
+{
+	local length="${#temporaryFiles[@]}"
+	local lastIndex
+	((lastIndex = --length))
+	echo "${temporaryFiles[$lastIndex]}"
+}
+
+function deleteTemporaryFile
+{
+	rm -f "$1" || printErrorHelpAndExit "Environment Error: Could not delete a temporary file ($1)." $invalidEnvironmentExitCode
+}
+
+function removeTemporaryFiles
+{
+	length="${#temporaryFiles[@]}"
+	if [ $length -eq 0 ]; then
+		return
+	fi
+	for temporaryFile in ${temporaryFiles[@]}; do
+		deleteTemporaryFile "$temporaryFile"
+	done
+	temporaryFiles=()
+	length="${#temporaryFiles[@]}"
+}
+
+function checkEnvironment
+{
+	programs=(openssl curl od dd printf sed awk sort mktemp rm grep cp ls env bash)
+	for program in "${programs[@]}"; do
+		checkProgramIsInEnvironment "$program"
+	done
+	
+	local temporaryFolder="${TMPDIR:-/tmp}"
+	if [ ! -x "$temporaryFolder" ]; then
+		printErrorHelpAndExit "Environment Error: The temporary directory ($temporaryFolder) does not exist. Please set the TMPDIR environment variable to your temporary directory" $invalidEnvironmentExitCode
+	fi
+	readonly temporaryDirectory="$temporaryFolder/s3-bash/$weAreKnownAs"
+	mkdir -p "$temporaryDirectory" || printErrorHelpAndExit "Environment Error: Could not create a temporary directory ($temporaryDiectory). Please check you /tmp folder permissions allow files and folders to be created and you have sufficient disc space" $invalidEnvironmentExitCode
+	
+	#Check we can create and delete temporary files
+	createTemporaryFile "check"
+	temporaryFileCheck="$(mostRecentTemporaryFile)"
+	echo "Checking we can write to temporary files. If this is still here then we could not delete temporary files." > "$temporaryFileCheck"
+	removeTemporaryFiles
+}
+
+function setErrorTraps
+{
+	trap "removeTemporaryFiles; exit $internalErrorExitCode" INT TERM EXIT
+}
+
+function unsetErrorTraps
+{
+	trap - INT TERM EXIT
 }
 
 function verifyUrl
 {
 	if [ -z "$url" ]; then
-		printErrorHelpAndExit "URL not specified" 1
+		printErrorHelpAndExit "URL not specified" $userSpecifiedDataErrorExitCode
 	elif echo $url | grep -q http://; then
-		printErrorHelpAndExit "URL starts with http://" 1
+		printErrorHelpAndExit "URL starts with http://" $userSpecifiedDataErrorExitCode
 	elif echo $url | grep -q https://; then
-		printErrorHelpAndExit "URL starts with https://" 1
+		printErrorHelpAndExit "URL starts with https://" $userSpecifiedDataErrorExitCode
 	elif echo $url | grep -v ^/; then
-		printErrorHelpAndExit "URL does not start with /" 1
+		printErrorHelpAndExit "URL does not start with /" $userSpecifiedDataErrorExitCode
 	fi
 }
 
@@ -110,7 +156,7 @@ function checkAwsKey
 	local originalKeyFile="$1"
 	local keySize="$(ls -l "$originalKeyFile" | awk '{ print $5 }')"
 	if [ ! $keySize -eq 40 ]; then
-		printErrorHelpAndExit "We do not understand Amazon AWS secret keys which are not 40 bytes long. Have you included a carriage return or line feed by mistak at the end of the secret key file?"
+		printErrorHelpAndExit "We do not understand Amazon AWS secret keys which are not 40 bytes long. Have you included a carriage return or line feed by mistake at the end of the secret key file?" $userSpecifiedDataErrorExitCode
 	fi
 }
 
@@ -125,7 +171,7 @@ function padDecodedKeyTo
 		local zerosToWrite=$((64 - $keySize))
 		dd if=/dev/zero of=$keyFile bs=1 count=$zerosToWrite seek=$keySize 2> /dev/null
 	elif [ $keySize -gt 64 ]; then
-		echo "Support for hashing keys bigger than the SHA1 block size of 64 bytes is untested" 1>&2
+		echo "Warning: Support for hashing keys bigger than the SHA1 block size of 64 bytes is untested" 1>&2
 		writeHash "$originalKeyFile" "$keyFile"
 		local keySize=$(ls -l "$keyFile" | awk '{ print $5 }')
 		if [ $keySize -lt 64 ]; then
@@ -209,12 +255,17 @@ function computeAwsAuthorizationHeader
 {
 	checkAwsKey "$awsAccessSecretKeyIdFile"
 	
-	local tempKeyFile="$(mktemp /tmp/$weAreKnownAs.key.XXXXXX)"
-	local ipadHashingFile="$(mktemp /tmp/$weAreKnownAs.ipad.XXXXXX)"
-	local opadHashingFile="$(mktemp /tmp/$weAreKnownAs.opad.XXXXXX)"
-	local hmacSha1File="$(mktemp /tmp/$weAreKnownAs.HMAC-SHA1.XXXXXX)"
-	local cleanUpCommand="rm -f "$tempKeyFile"; rm -f "$ipadHashingFile"; rm -f "$opadHashingFile"; rm -f "$hmacSha1File""
-	trap "$cleanUpCommand; exit 1" INT TERM EXIT
+	createTemporaryFile "key"
+	local tempKeyFile="$(mostRecentTemporaryFile)"
+	
+	createTemporaryFile "ipad"
+	local ipadHashingFile="$(mostRecentTemporaryFile)"
+	
+	createTemporaryFile "opad"
+	local opadHashingFile="$(mostRecentTemporaryFile)"
+	
+	createTemporaryFile "HMAC-SHA1"
+	local hmacSha1File="$(mostRecentTemporaryFile)"
 
 	padDecodedKeyTo "$awsAccessSecretKeyIdFile" "$tempKeyFile"
 	readBytesAndXorAndWriteAsBytesTo "$tempKeyFile" ipadXorByte "$ipadHashingFile"
@@ -227,18 +278,15 @@ function computeAwsAuthorizationHeader
 
 	local signature="$($base64encode "$hmacSha1File")"
 
-	$cleanUpCommand
-	trap - INT TERM EXIT
-
 	echo "Authorization: AWS $awsAccessKeyId:$signature"
 }
 
 function writeAmazonHeadersForCurl
 {
 	if [ ! -e "$amazonHeaderFile" ]; then
-		printErrorHelpAndExit "Amazon Header file does not exist" 1
+		printErrorHelpAndExit "Amazon Header file does not exist" $userSpecifiedDataErrorExitCode
 	elif grep -q ^X-Amz-Date: "$amazonHeaderFile"; then
-		printErrorHelpAndExit "X-Amz-Date header not allowed" 1
+		printErrorHelpAndExit "X-Amz-Date header not allowed" $userSpecifiedDataErrorExitCode
 	fi
 	# Consider using sed...
 	awk 'BEGIN { ORS=" "; FS="\0" } { print "--header \"" $1 "\""}' "$amazonHeaderFile" >> "$1"
@@ -248,11 +296,11 @@ function runCurl
 {
 	local verbAndAnyData="$1"
 	local fullUrl="$protocol://s3.amazonaws.com$url"
-	local tempCurlCommand="$(mktemp /tmp/$weAreKnownAs.curl.XXXXXX)"
+	createTemporaryFile "curl"
+	local tempCurlCommand="$(mostRecentTemporaryFile)"
 	local cleanUpCommand="rm -f "$tempCurlCommand""
-	#trap "$cleanUpCommand; exit 1" INT TERM EXIT
 
-	echo "#! /bin/bash" >> "$tempCurlCommand"
+	echo "#! /usr/bin/env bash" >> "$tempCurlCommand"
 	printf "curl %s %s --dump-header \"%s\" " "$verbose" "$verbAndAnyData" "$dumpHeaderFile" >> "$tempCurlCommand"
 	writeAmazonHeadersForCurl "$tempCurlCommand"
 	printf " --header \"%s\"" "Date: $currentDateTime" >> "$tempCurlCommand"
@@ -264,10 +312,23 @@ function runCurl
 		printf " --header \"Content-MD5: %s\"" "$contentMD5" >> "$tempCurlCommand"
 	fi
 	printf " \"%s\"\n" "$fullUrl" >> "$tempCurlCommand"
-
-	/bin/bash "$tempCurlCommand"
-
-	#$cleanUpCommand
-	trap - INT TERM EXIT
+	
+	unsetErrorTraps
+	exec env bash "$tempCurlCommand"
 }
 
+function initialise
+{
+	setErrorTraps
+	checkEnvironment
+}
+
+function main
+{
+	initialise
+	parseOptions "$@"
+	readonly currentDateTime="$(LC_TIME=C date "+%a, %d %h %Y %T %z")"
+	prepareToRunCurl
+	readonly authorizationHeader="$(computeAwsAuthorizationHeader)"
+	runCurl "$verbToPass"
+}
